language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  - "python setup.py install"

script: nosetests

after_success:
  - pip install coveralls
  - coverage run --source=werobot setup.py -q nosetests
  - coveralls

notifications:
  email: false
